## stochastic gradient descent

In [13]:
import torch

In [14]:
w = torch.tensor([[8.0]], requires_grad=True)
alpha = 0.1
for step in range(1000):
    loss_function = (w[0] - 7.0)**2
    loss_function.backward()
    w.data = alpha * w.grad
    w.grad.zero_()
    print(w, step)

tensor([[0.2000]], requires_grad=True) 0
tensor([[-1.3600]], requires_grad=True) 1
tensor([[-1.6720]], requires_grad=True) 2
tensor([[-1.7344]], requires_grad=True) 3
tensor([[-1.7469]], requires_grad=True) 4
tensor([[-1.7494]], requires_grad=True) 5
tensor([[-1.7499]], requires_grad=True) 6
tensor([[-1.7500]], requires_grad=True) 7
tensor([[-1.7500]], requires_grad=True) 8
tensor([[-1.7500]], requires_grad=True) 9
tensor([[-1.7500]], requires_grad=True) 10
tensor([[-1.7500]], requires_grad=True) 11
tensor([[-1.7500]], requires_grad=True) 12
tensor([[-1.7500]], requires_grad=True) 13
tensor([[-1.7500]], requires_grad=True) 14
tensor([[-1.7500]], requires_grad=True) 15
tensor([[-1.7500]], requires_grad=True) 16
tensor([[-1.7500]], requires_grad=True) 17
tensor([[-1.7500]], requires_grad=True) 18
tensor([[-1.7500]], requires_grad=True) 19
tensor([[-1.7500]], requires_grad=True) 20
tensor([[-1.7500]], requires_grad=True) 21
tensor([[-1.7500]], requires_grad=True) 22
tensor([[-1.7500]], re